### PR TITLE
Catch MongoDBExceptions to throw ModelManagerExceptions

### LINKED ISSUE #790: AbstractAdmin create method does not handle Model manager create exceptions
### Environment

Ubuntu 22.04 Jammy Jellyfish

#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
Direct dependencies required in composer.json:
sonata-project/admin-bundle                  4.20.0 4.20.0 The missing Symfony Admin Generator
sonata-project/doctrine-mongodb-admin-bundle 4.6.0  4.6.0  Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/user-bundle                   5.4.0  5.4.0  Symfony SonataUserBundle

Transitive dependencies not required in composer.json:
sonata-project/block-bundle                  4.19.0 4.19.0 Symfony SonataBlockBundle
sonata-project/cache                         2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions           2.0.1  2.0.1  Doctrine2 behavioral extensions
sonata-project/exporter                      3.0.0  3.0.0  Lightweight Exporter library
sonata-project/form-extensions               1.18.0 1.18.0 Symfony form extensions
sonata-project/twig-extensions               2.0.0  2.0.0  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
Direct dependencies required in composer.json:
symfony/asset                      v6.1.5  v6.1.5  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v6.1.3  v6.1.3  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/console                    v6.1.7  v6.1.7  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v6.1.3  v6.1.3  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v6.1.3  v6.1.3  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/doctrine-messenger         v6.1.4  v6.1.4  Symfony Doctrine Messenger Bridge
symfony/dotenv                     v6.1.0  v6.1.0  Registers environment variables from a .env file
symfony/expression-language        v6.1.6  v6.1.6  Provides an engine that can compile and evaluate expressions
symfony/flex                       v2.2.3  v2.2.3  Composer plugin for Symfony
symfony/form                       v6.1.7  v6.1.7  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v6.1.7  v6.1.7  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v6.1.7  v6.1.7  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/intl                       v6.1.7  v6.1.7  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v6.1.7  v6.1.7  Helps sending emails
symfony/maker-bundle               v1.47.0 v1.47.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mercure-bundle             v0.3.5  v0.3.5  Symfony MercureBundle
symfony/mime                       v6.1.7  v6.1.7  Allows manipulating MIME messages
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/notifier                   v6.1.0  v6.1.0  Sends notifications via one or more channels (email, SMS, ...)
symfony/phpunit-bridge             v6.1.6  v6.1.6  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/process                    v6.1.3  v6.1.3  Executes commands in sub-processes
symfony/property-access            v6.1.7  v6.1.7  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v6.1.7  v6.1.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v6.1.0  v6.1.0  Provides integration for ProxyManager with various Symfony components
symfony/runtime                    v6.1.3  v6.1.3  Enables decoupling PHP applications from global state
symfony/security-bundle            v6.1.3  v6.1.3  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/serializer                 v6.1.6  v6.1.6  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/stopwatch                  v6.1.5  v6.1.5  Provides a way to profile code
symfony/string                     v6.1.7  v6.1.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v6.1.6  v6.1.6  Provides tools to internationalize your application
symfony/twig-bundle                v6.1.1  v6.1.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v6.1.7  v6.1.7  Provides tools to validate values
symfony/web-link                   v6.1.0  v6.1.0  Manages links between resources
symfony/web-profiler-bundle        v6.1.6  v6.1.6  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v6.1.6  v6.1.6  Loads and dumps YAML files

Transitive dependencies not required in composer.json:
symfony/cache                      v6.1.7  v6.1.7  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            v3.1.1  v3.1.1  Generic abstractions related to caching
symfony/config                     v6.1.3  v6.1.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/dependency-injection       v6.1.5  v6.1.5  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.1.1  v3.1.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v6.1.7  v6.1.7  Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                v6.1.7  v6.1.7  Eases DOM navigation for HTML and XML documents
symfony/error-handler              v6.1.7  v6.1.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v6.1.0  v6.1.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.1.1  v3.1.1  Generic abstractions related to dispatching event
symfony/filesystem                 v6.1.5  v6.1.5  Provides basic utilities for the filesystem
symfony/finder                     v6.1.3  v6.1.3  Finds files and directories via an intuitive fluent interface
symfony/http-client-contracts      v3.1.1  v3.1.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v6.1.7  v6.1.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v6.1.7  v6.1.7  Provides a structured process for converting a Request into a Response
symfony/mercure                    v0.6.1  v0.6.1  Symfony Mercure Component
symfony/messenger                  v6.1.6  v6.1.6  Helps applications send and receive messages to/from other applications or via message queues
symfony/monolog-bridge             v6.1.2  v6.1.2  Provides integration for Monolog with various Symfony components
symfony/options-resolver           v6.1.0  v6.1.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v6.1.3  v6.1.3  Provides password hashing utilities
symfony/polyfill-intl-grapheme     v1.26.0 v1.26.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.26.0 v1.26.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.26.0 v1.26.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.26.0 v1.26.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.26.0 v1.26.0 Symfony polyfill for the Mbstring extension
symfony/routing                    v6.1.7  v6.1.7  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-core              v6.1.7  v6.1.7  Symfony Security Component - Core Library
symfony/security-csrf              v6.1.0  v6.1.0  Symfony Security Component - CSRF Library
symfony/security-http              v6.1.7  v6.1.7  Symfony Security Component - HTTP Integration
symfony/service-contracts          v3.1.1  v3.1.1  Generic abstractions related to writing services
symfony/translation-contracts      v3.1.1  v3.1.1  Generic abstractions related to translation
symfony/twig-bridge                v6.1.7  v6.1.7  Provides integration for Twig with various Symfony components
symfony/var-dumper                 v6.1.6  v6.1.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.1.3  v6.1.3  Allows exporting any serializable PHP data structure to plain PHP code
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.1.2-1ubuntu2.6 (cli) (built: Sep 15 2022 11:30:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.6, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

## Subject

MongoDB unique index (created with `#[ODM\Index(unique: true)]` annotation) errors are not intercepted by AbstractAdmin.
If an exception is thrown by `$this->getModelManager()->create($object);` at line 412 of `AbstractAdmin.php`, in the `create` method, it break the admin.

In some cases, (e.g a Gedmo slug field), Unique constraints are not triggered, and the non-unique value is sent to the database. It trigger an exception not intercepted by AbstractAdmin::create() method.

## Steps to reproduce

Create this document (get & setters may be needed):

```php
use Doctrine\Bundle\MongoDBBundle\Validator\Constraints as ODMConstraints;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints;

#[ODM\Document()]
#[ODMConstraints\Unique(fields: ['name'])]
#[ODMConstraints\Unique(fields: ['slug'])]
class BaseItem
{
    /**
     * This document UUID identifier.
     */
    #[ODM\Id(strategy: 'UUID')]
    protected ?string $id;

    /**
     * The name.
     */
    #[ODM\Field(type: 'string')]
    #[ODM\Index(unique: true)]
    #[Constraints\NotBlank()]
    protected string $name;

    /**
     * A slug, based on name.
     */
    #[ODM\Field(type: 'string')]
    #[ODM\Index(unique: true)]
    #[Gedmo\Slug(fields: ['name'], unique: false)]
    protected ?string $slug = null;
}
```

Add a new item named "Test", and then add a item named "test". The slug for both document is "test".

## Expected results

An error is displayed to the user.

## Actual results

The exception is a `MongoDB\Driver\Exception\ BulkWriteException` with message:

```log
E11000 duplicate key error collection: database.BaseItem index: slug_1 dup key: { slug: "test" }
```

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Closes #790

## Changelog

```markdown
### Fixed
- Catch and display error messages when creating updating or remove objects
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

File: src/Model/ModelManager.php [hunk 1]
```diff
@@ -207,17 +234,26 @@ public function batchDelete(string $class, BaseProxyQueryInterface $query): void
...
             }
-        }
 
-        $documentManager->flush();
-        $documentManager->clear();
+            $documentManager->flush();
+            $documentManager->clear();
+        } catch (Exception|MongoDBException $exception) {
+            throw new ModelManagerException(
+                sprintf('Failed to delete object: %s', $class),
```
Comment (phansys) [inline src/Model/ModelManager.php:252]: IIUC, this exception is thrown if the removal of a single object fails, but it does not include a reference for that object (its id or something else). Additionally, if the removal of a single object fails, the previous processed transactions are not reverted, so just mentioning the object class without a reference seems sub-optimal.

Comment (jordisala1991) [reply src/Model/ModelManager.php:252]: Take a look at how it is implemented on the orm side: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/4.x/src/Model/ModelManager.php#L348

I just copied the same code and adapted for odm the exceptions.

Comment (phansys) [reply src/Model/ModelManager.php:252]: Maybe we should improve this message for both managers then.
WDYT?

Comment (jordisala1991) [reply src/Model/ModelManager.php:252]: Yes it could be improved, but IMO it should be done in another PR. Here I am just trying to match behaviors of both persistence bundles and to avoid unexpected exceptions.

Also I am not familiar enough with MongoDB to know if there are transactions, and how to properly test that (I would do that other change you propose in another PR too).

**Review by phansys — APPROVED** [review]
