### PR TITLE
fix form and filter template registration

### LINKED ISSUE #583: Form/Filter Templates broken with admin 3.98.2
Similar to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1427 we need to make sure we merge the `setFormTheme` and `setFilterTheme` calls as now on Sonata admin 3.98.2+ we are adding those calls as well.

So currently the templates of this bundle are not properly configured anymore when using admin bundle 3.98.2+.

### PR DESCRIPTION
**Pull request by dmaicher**
## Subject

I am targeting this branch, because its a bug fix.

Closes #583 

## Changelog

```markdown
### Deprecated
- `templates.form` and `templates.filter` config

### Fixed
- Always merge form and filter templates with existing method calls
```

### CODE REVIEW

**Comment by dmaicher** [comment]
Failures are unrelated

File: src/DependencyInjection/Compiler/AddGuesserCompilerPass.php [hunk 1]
```diff
@@ -18,8 +18,12 @@
 use Symfony\Component\DependencyInjection\Reference;
 
 /**
+ * NEXT_MAJOR: Remove the "since" part of the internal annotation.
+ *
  * @author Thomas Rabaix <thomas.rabaix@sonata-project.org>
  *
+ * @internal since sonata-project/doctrine-orm-admin-bundle version 4.0
```
Comment (VincentLanglet) [inline src/DependencyInjection/Compiler/AddGuesserCompilerPass.php:25]: It's not `doctrine-orm-admin-bundle` ;) (same for others)

**Comment by VincentLanglet** [comment]
I think you can solve the phpstan issue by adding phpdoc to the `execute` method of the ProxyQuery in order to have a more precise return type. But I don't know what is the return type of the execute method, is it ArrayCollection ? @franmomu

**Review by VincentLanglet — APPROVED** [review]
